Veeb/Õpilased/Õpilased/Models/Õpilane.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Õpilased.Models
{
    public class Õpilane
    {
        // PROPERTY'd
        [Key]
        [Display(Name = "Isikukood")]
        public string IK { get; set; }
        public string Nimi { get; set; }
        public string Klass { get; set; }
        private static Dictionary<string, Õpilane> _Õpilased = new Dictionary<string, Õpilane>(); // see on dictionary, kus hakkan õpilaisi hoidma
        public static IEnumerable<Õpilane> Õpilased => _Õpilased.Values; // see on avalik "List", mis sisaldab õpilaisi

        // Add funktsioon lisab õpilase dictionary, kui teda seal ei ole
        public bool Add()
        {
            if (!_Õpilased.ContainsKey(this.IK))
            {
                _Õpilased.Add(IK, this);
                return true;
            }
            else return false;
        }

        // FUNKTSIOONID
        // find funktsioon leiab õpilase dictionarist
        public static Õpilane Find(string ik)
            => _Õpilased.ContainsKey(ik) ? _Õpilased[ik] : null;

        // delete meetod kustutab ta dictionarist
        public void Delete()
        {
            if (_Õpilased.ContainsKey(this.IK)) _Õpilased.Remove(this.IK);
        }
    }
}

Veeb/Õpilased/Õpilased/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Õpilased.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Veeb/Õpilased/Õpilased/Controllers/ÕpilaneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Õpilased.Models;

namespace Õpilased.Controllers
{
    public class ÕpilaneController : Controller
    {
        // GET: Õpilane
        public ActionResult Index()
        {
            return View(Õpilane.Õpilased);
        }

        // GET: Õpilane/Details/5
        public ActionResult Details(string id)
        {
            Õpilane õ = Õpilane.Find(id);
            if (õ == null)
                return HttpNotFound();
            return View(õ);
        }

        // GET: Õpilane/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Õpilane/Create
        [HttpPost]
        public ActionResult Create(Õpilane õpilane)
        {

            // TODO: Add insert logic here
            if (õpilane.Add())
                return RedirectToAction("Index");

            else
            {
                ViewBag.Error = "selline isikood juba eksisteerib";
                return View(õpilane);
            }
        }

        // GET: Õpilane/Edit/5
        public ActionResult Edit(string id)
        {
            Õpilane õ = Õpilane.Find(id);
            if (õ == null) return HttpNotFound();
            return View(õ);
        }

        // POST: Õpilane/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, Õpilane õpilane)
        {
            Õpilane õ = Õpilane.Find(id);
            try
            {
                // TODO: Add update logic here
                if (õ != null)
                {
                    õ.Nimi = õpilane.Nimi;
                    õ.Klass = õpilane.Klass;
                }
                  
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Õpilane/Delete/5
        public ActionResult Delete(string id)
        {
            return View();
        }

        // POST: Õpilane/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Õpilane.Find(id)?.Delete();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(Õpilane.Find(id));
            }
        }
    }
}

Veeb/Õpilased/Õpilased/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Veeb/Õpilased/Õpilased/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Veeb/Õpilased/Õpilased/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Veeb/Õpilased/Õpilased/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Õpilased", "Index", "Õpilane")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Minu ASP.NET Aplikatsioon</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Veeb/Õpilased/Õpilased/Views/Õpilane/Create.cshtml
@model Õpilased.Models.Õpilane

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Õpilane</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IK, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IK, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IK, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nimi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nimi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nimi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Klass, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Klass, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Klass, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Veeb/Õpilased/Õpilased/Views/Õpilane/Delete.cshtml
@model Õpilased.Models.Õpilane

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Õpilane</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Klass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Klass)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Veeb/Õpilased/Õpilased/Views/Õpilane/Details.cshtml
@model Õpilased.Models.Õpilane

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Õpilane</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Klass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Klass)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IK }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Veeb/Õpilased/Õpilased/Views/Õpilane/Edit.cshtml
@model Õpilased.Models.Õpilane

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Õpilane</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IK)

        <div class="form-group">
            @Html.LabelFor(model => model.Nimi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nimi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Klass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Klass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Klass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Veeb/Õpilased/Õpilased/Views/Õpilane/Index.cshtml
@model IEnumerable<Õpilased.Models.Õpilane>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Klass)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nimi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Klass)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IK }) |
            @Html.ActionLink("Details", "Details", new { id=item.IK }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IK })
        </td>
    </tr>
}

</table>